#' Assign Coalition Labels to a Game Vector
#'
#' This function assigns string labels to the elements of a numeric vector `v`,
#' which represents the value of a cooperative game. Each label corresponds to
#' a non-empty coalition of players. The function assumes the vector is ordered
#' according to the standard ordering of coalitions used in cooperative game theory.
#'
#' @param v A numeric vector representing the values of the coalitions in a cooperative game.
#' The length must be equal to 2^n - 1 for some integer n (number of players).
#'
#' @return The same vector `v`, but with names (labels) assigned to each element.
#'
#' @details This function is compatible with vectors generated by the CoopGame package.
#' It does not depend on CoopGame internally, so it can be used independently.
#'
#' @examples
#' # For internal testing purposes only:
#' v <- c(0,0,0,60,60,60,100)
#' set_label_game(v)
#'
#' @export
set_label_game <- function(v) {
  n <- log2(length(v) + 1)

  if (!isTRUE(all.equal(n, as.integer(n)))) {
    stop("Length of input vector is not valid: must be 2^n - 1 for some integer n.")
  }

  labels <- get_index_set(as.integer(n))
  names(v) <- labels
  return(v)
}
